#title: Just the Docs Template
title: Backtesting
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

repository              : muellerh08/bs-jtd
url                     : https://github.com/muellerh08/bs-jtd
baseurl: ""
plugins:
  - jekyll-default-layout

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections_dir: coll
collections:
  ik:
    output: true

bs-jtd:
  collections:
    ik:
    name: Ik
